#DROP DATABASE demo;
CREATE DATABASE demo;
USE demo;

CREATE TABLE MOUNTAIN (
       ID INT (11) NOT NULL AUTO_INCREMENT
     , MOUNTAIN_NAME VARCHAR(25) NOT NULL
     , MOUNTAIN_ELEV VARCHAR(5) NOT NULL
     , MOUNTAIN_IMG VARCHAR(100)
     , VERSION INT NOT NULL DEFAULT 0
     , UNIQUE UQ_MOUNTAIN_1 (MOUNTAIN_NAME)
     , PRIMARY KEY (ID)
);

INSERT INTO MOUNTAIN (MOUNTAIN_NAME, MOUNTAIN_ELEV, MOUNTAIN_IMG) VALUE ('Mt. Washington', '6,288', 'Washington-StoryImage_2-5.jpg');
INSERT INTO MOUNTAIN (MOUNTAIN_NAME, MOUNTAIN_ELEV, MOUNTAIN_IMG) VALUE ('Mt. Adams"', '5,799', 'Adams-StoryImage_2-5.jpg');
INSERT INTO MOUNTAIN (MOUNTAIN_NAME, MOUNTAIN_ELEV, MOUNTAIN_IMG) VALUE ('Mt. Jefferson', '5,716', 'Jefferson-StoryImage_2-5.jpg');
INSERT INTO MOUNTAIN (MOUNTAIN_NAME, MOUNTAIN_ELEV, MOUNTAIN_IMG) VALUE ('Mt. Monroe', '5,372', 'Monroe-StoryImage_2-5.jpg');
INSERT INTO MOUNTAIN (MOUNTAIN_NAME, MOUNTAIN_ELEV, MOUNTAIN_IMG) VALUE ('Mt. Madison', '5,366', 'Madison-StoryImage_2-5.jpg');
INSERT INTO MOUNTAIN (MOUNTAIN_NAME, MOUNTAIN_ELEV, MOUNTAIN_IMG) VALUE ('Mt. Lafayette', '5,260', 'Lafayette-StoryImage_2-5.jpg');
